### ISSUE TITLE
`unbind` removes all handlers

### ISSUE THREAD

**Issue by fallafeljan** [deitch/smtp-tester#12] opened 2017-01-19 10:48 UTC
I understood from the Readme that `unbind`, given a handler that was previously bound to the server, should only remove the respective handler. However, `unbind` currently unbinds all handlers that have been bound previously:

```js
mailServer.bind(handler1);
mailServer.bind(handler2);

mailServer.unbind(handler2);
```

This will result in `handler1` not being called. If wanted, I'll do a PR that fixes this behaviour 🛠

**Comment by deitch** [comment] 2017-01-19 12:22
The code looks right. `unbind()` is used in the tests, although not specifically tested. 

> If wanted, I'll do a PR that fixes this behaviour

Happy to take it, thank you. Do you know where the issue is?

**Comment by fallafeljan** [comment] 2017-01-19 14:27
Yes, there was a bug in `unbind` (`var tmp = []`, `handlers = tmp`) that caused the iterator not to run (because after calling `unbind` once, `handlers` was an array instead of an object, and `_.each` does only run on arrays. All handlers vanished then.

**Comment by deitch** [comment] 2017-01-19 17:45
Closing in favour of #13

**Closed by deitch** 2017-01-19 17:45 UTC
